export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILURE';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

//export const DASHBOARD_LOAD = 'DASHBOARD_LOAD';

export const DASHBOARD_REQUEST_DATA = 'DASHBOARD_REQUEST_DATA';
export const DASHBOARD_REFRESH_START = 'DASHBOARD_REFRESH_START';
export const DASHBOARD_REFRESH_SUCCESS = 'DASHBOARD_REFRESH_SUCCESS';
export const DASHBOARD_REFRESH_FAILURE = 'DASHBOARD_REFRESH_FAILURE';

